### ISSUE TITLE
too slow when counting

### ISSUE THREAD

**Issue by sparse91** [nitmir/policyd-rate-limit#11]
Hi
I have installed policyd on Debian 9 + postfix.
Each policyd count takes one seconds. Therefore it takes many seconds for an email with multiple recipients to be send! I don't know if this is normal or my setup has a problem.
I tested it with both Mariadb and SQLite. I'll be glad if you can help.
Thanks

**Comment by nitmir** [comment]
Which version are you using ? (a tagged release or master ?)
It is highly probable that your problem was fixed by #10

**Comment by sparse91** [comment]
policyd-rate-limit/stable,now 0.7.1-1 all
OK. I'll try it when it updates in Debian 9. Thanks

**Comment by P-EB** [comment]
@sparse91 it was partially fixed, sadly I introduced an error that made the accounting crappy. I fixed it in a later commit, which has been merged in Debian 10.

**Comment by sparse91** [comment]
It's working well on Debian 10.
